### ISSUE TITLE
Can't seem to install animdessin :(

### ISSUE THREAD

**Issue by kickingfrogleg** [sbaril/Photoshop-Animation#10]
I used to use it for years until my CC account changed, and now it just doesn't show up on Adobe Exchange, and it doesn't show up on my photoshop either. Need to urgently install it for a big project I am working on, is there any other way? 
I have tried with Anastasiy Extension Manager, but it won't even read my photoshop. (I use Photoshop CC 2020)

**Comment by schroef** [comment]
You can also try downloading to download this repo and than use the SRC folder. you need to change its name to ```com.sbaril.animdessign2``` and drop that into the CEP folder on your system. On MacOS that path is either ```/Library/Application Support/Adobe/CEP/``` or ```~/Library/Application Support/Adobe/CEP/```, i don't know Windows paths.

I tried this last week when a different user also had install issues and it worked fine for me. The extension should show.

PS if you head over to my repo, you can use a version i have been working on. Ive added many new options, including a help panel with all key-combos, many buttons have now 2-4 options per click. You can see this post ( #8 ) what I've been adding. Installing my version is the same way as i described above.
https://github.com/schroef/AnimDessin2

**Comment by kickingfrogleg** [comment]
Hi, thanks, I tried that but it still isn't showing up - I have this folder "com.sbaril.animdessin2" in both CEP and ~CEP folders, but it is still not showing up in my photoshop extension drop down menu. I tried with yours as well, still no luck. PS: I'm not familiar with coding at all, so if this requires anything other than a copy paste, you will have to walk me through it! I am not sure what a src folder is, could you help explain it to me?

**Comment by sbaril** [comment]
Can you try again with this direct link to download AnimDessin2:
[(https://github.com/sbaril/Photoshop-Animation/blob/master/AnimDessin2_CC18.zxp)]
And the last version of Anastasyi: [http://install.anastasiy.com/]
If you are on Windows, after unzipping it, can you Right-Click on "ExtensionManager.exe" and choose "Run as Administrator" to launch it in place of double-clicking on it.

**Comment by kickingfrogleg** [comment]
Hey! I'm on a mac - I get this error every time I open Extension Manager(it is the new one) : _Cannot read installed extensions information. Please try to run Extension Manager as Administrator and make sure all installation files are in place._
 I don't have the option to run as administrator when I right-click, is there another way?

**Comment by sbaril** [comment]
I just deinstalled my WIP version on my Mac and reinstalled it to test.
FYI: _Run as Administrator was jut an extra tip in case you were on Windows._

It's seems the direct download is corrupting the ZXP _(it's a sort of ZIP so it can happen…)_ and I was not able to install it neither because it was corrupted.
But, when I downloaded the ZIP using the green "**Clone or download**" button, then "**Download ZIP**", it worked for me on my Mac on Catalina 10.15.4.

Please let me know if that works for you.

**Comment by schroef** [comment]
Okay its perhaps running on my side because some kind of cache then i guess. Hope you get it working with the new explanation by @sbaril

**Comment by kickingfrogleg** [comment]
Hi, so tried that as well, I get this message on Anastasiy: _Installation was successful! Please restart Adobe application if it's open before usage._
But when I open photoshop it still doesn't show in my extensions. And theres some issue with uninstalling it as well, CC just isnt recognising it on my computer anymore

**Comment by schroef** [comment]
Ow sorry perhaps i wasnt clear. My version cant be installed using that Anastaciy app. You need to manually drop it into the CEP extension folder. It should give a warning i guess since its not an ZXP file

**Comment by schroef** [comment]
I had a small issue with the Locale, I believe it should be fixed now. Im currently on my super old MacBook because my MacBook pro has big issues. So I'm also using 2017 cc and it didn't show neither. Thats how I found the issue with the Localize, it is showing now. THough is also saw CSS issues, these older version of PS cant handle variables in CSS, so that's is fixed. One other things which doesn't seem to work, are the videos. Since the CEP engine is older it doesn't have the proper SSL for the video stream, that such :( So I need to figure out how to hide that on older PS versions.

**Comment by kickingfrogleg** [comment]
I've uninstalled and reinstalled all my software but still no sight of the Animdessin extension in my Photoshop (CC 2020), it works perfectly fine on my iMac (which is at the office), but as I'm working from home now, it's just not showing up in my laptop (Macbook pro 2015 - Mojave 10.14.6), no matter what I do here. I have tried the folder method, the .zxp method, the CC extension manager method, and the Anastasiy method - none are working! Have given up at this point :(

**Comment by kickingfrogleg** [comment]
Really love this product, so it's very disappointing for me not to be able to use it!

**Comment by sbaril** [comment]
So perhaps (my last idea), try again the schroef recommandation of copying is folder in the CEP > extensions folder
… but to allow this to works that way, you need to enable the debug mode:
In your Mac open the Terminal app and paste this line: 
_defaults write com.adobe.CSXS.9 PlayerDebugMode 1_
and tap Enter in your keyboard.

PS: if for any reason you want to disable the debug mode later:
_defaults write com.adobe.CSXS.9 PlayerDebugMode 0_

**Comment by schroef** [comment]
But this uses older CEP so just incase add a couple :)
SO also add these, just in case. It allows you to run the extension without signing. It WONT do harm!!

I'm using CEP 7 so I believe with CSXS7 it should show now. Otherwise we need to check what has changed since the new CEP engine. It could be that we need to port it to CEP 9 for that. But I believe they are all backward compatible, at least I think I read that

```
defaults write com.adobe.CSXS.7 PlayerDebugMode 1
defaults write com.adobe.CSXS.8 PlayerDebugMode 1
```

**Comment by schroef** [comment]
PS i also made a test ZXP release, I'm not 100% sure it will work properly. I made a test signature, it worked for me locally on blank install

you can find it here
https://github.com/schroef/AnimDessin2/releases

**Comment by kickingfrogleg** [comment]
It worked!!!!!! Thank you soooo much, both of you - you've been very helpful! 💙

**Comment by sbaril** [comment]
You're welcome :)

So I'm closing the issue now.

**Comment by schroef** [comment]
> It worked!!!!!! Thank you soooo much, both of you - you've been very helpful! 💙

Which version are you using now? If your using mine let me know if you find issues or stuff which doesn't work. I got lots of options and tried to test all of them. Most should work just fine.

**Comment by Renegade1765** [comment]
Hey! I've got a massive problem. I want to use Photoshop to do my animations, but I need Anim Dessin 2 to use its full potential. Problem is that every time I try to install it with Adobe Extension Manager, it always gives me this message. I need help.


![](https://user-images.githubusercontent.com/75491653/101834817-7fecb900-3b43-11eb-8e46-1712602b6579.JPG)

**Comment by schroef** [comment]
@Renegade1765, ive replied in your other thread #15
