### ISSUE TITLE
AnimDessin2 incompatible with Photoshop CC 2022 ?

### ISSUE THREAD

**Issue by nicoleswardh** [sbaril/Photoshop-Animation#25]
Hey ! just wondering if AnimDessin is compatible with any versions of photoshop between 22.0 up to 23.5.1 ? Just for context, I'm in animation school and my teacher is having us animate on photoshop for a specific assignment. I'm trying to install AnimDessin2 on my school computer. a Macbook Pro, but the extentions tab that should be under the windows drop-down menu doesn't even come up. I've had AnimDessin2 on my personal computer -Windows- before, but this plugin just doesn't seem to work for the 2022 version of Photoshop.

If there's any way of applying these plugins to any recent Photoshop versions, please let me know !

**Comment by plindale** [comment]
I have it running on 23.5.1 on a 2021 Macbook Pro. It works perfectly apart from the function to create a new AnimDessin2 file, which gives an error and only partially works. Note: AnimDessin2 does not work on Macs with the M1 chip - for those I use a series of animation actions I created that emulate and expand on AnimDessin2’s most useful functions.

I've heard of the missing extensions menu issue but have not come across it myself. It could be due to the M1 chip.

https://community.adobe.com/t5/photoshop-ecosystem-discussions/p-extensions-missing-after-updating-to-photoshop-22-3/m-p/11886711/page/2

Paul Lindale
Professor, Art Department
Greenfield Community College
One College Drive
Greenfield, MA 01301

art.gcc.mass.edu

**Comment by nicoleswardh** [comment]
Hello hello ! thank you so much for your reply. Turns out, I got it to work ! I read what different people had to say in the page you linked, and turns out, all I had to do was to open Photoshop with Rosetta.

(by right clicking Photoshop on Finder and selecting "get Info" > "Open with Rosetta". From there, AnimDessin2 works perfectly fine.)

Thank you again for your reply!
