### ISSUE TITLE
Can't install AnimDessin :(

### ISSUE THREAD

**Issue by maekart** [sbaril/Photoshop-Animation#9]
Hello guys, 

I’m trying to install AnimDessin but running into some problems. I'm trying to install it from here but when I use Adobe Extension manager it says it's only valid between 14 and 16.9. I have v19.1.5.

When I use Anistasy Extension Manager, it says it's already been installed. But it doesn't appear in my Photoshop extensions.

Thank you!

**Comment by schroef** [comment]
If you install it from here. Simply rename the AnimDession2 to "com.sbaril.annimdessin2". This folder is found in this repo in scr folder. Then use cmd + G on mac, if you use mac??? then add this line
```
/Library/Application Support/Adobe/CEP/
```
This will move you to the CEP folder, the folder with all panels. You can also add ~ if you want it in the user folder. If there is no "Extensions" folder present, create one. I doubt it because tons of folders are added by Adobe apps. 

One restarting Photoshop it should appear, that is still cc 2018 right?

I just tested this workflow here and it still works.

PS if you want a bold experience, try my upgraded version of the panel. Ive been working on it for 3 weeks daily now and just finished, i think. It has many more features and options now

You can find mine here; https://github.com/schroef/AnimDessin2
Its code from this repo and i simply been adding new stuff. Its way more powerful now than this current repo.

**Comment by sbaril** [comment]
Hi maekart,
Most of the time users have issue to install is because they are using the "Adobe Extension Manager CC" (end of life in 2014) in place the Anastasiy's one: [http://install.anastasiy.com]
Checkin with you just in case.
Another issue is, on some Windows confit, to open to Anastasiy "ExtensionManager.exe" by right-clicking on the App and choose "Run as administrator", the install the ZXP

Please let me know how it works!

**Comment by maekart** [comment]
Thanks! I was able to install it! :))))

**Comment by schroef** [comment]
@maekart did you also tried my version? I would like to know if it works on other OS or any issues you run into. On my system everything works fine, i cant test other OS's here
